sudo: required
services:
  - docker
 
before_install:
  - docker build -t bpatmiller/brendanmillerio-docker -f Dockerfile.dev .
 
script:
  - docker run -e CI=true -it bpatmiller/brendanmillerio-docker npm run test -- --coverage