sudo: required
services:
  - docker
 
before_install:
  - docker build -t bpatmiller/brendanmillerio-docker -f Dockerfile.dev .
 
script:
  - docker run -rm -e CI=true -it bpatmiller/brendanmillerio-docker npm run test -- --coverage

deploy:
  - ssh ubuntu@brendanmiller.io 'yes | docker system prune; rm -rf brendanmiller.io; git clone https://github.com/bpatmiller/brendanmiller.io.git;'
  - ssh ubuntu@brendanmiller.io 'cd brendanmiller.io && docker build -t bpatmiller/brendanmillerio-docker-dep -f Dockerfile.dep . && docker run -rm -d --network host bpatmiller/brendanmillerio-docker-dep'