FROM node:alpine as build-deps
WORKDIR '/app'
COPY ./package.json .
RUN npm install
COPY ./ ./
RUN npm run build

FROM node:alpine
RUN npm install -g serve
COPY --from=build-deps /app/build /app/build
EXPOSE 80
CMD ["serve", "-s", "build", "-l", "80"]